#!/usr/bin/env bash
#
# init-secrets.sh
#
# Generates the gitignored .env file containing all the secrets and
# environment-specific settings required by the Docker Compose stack.
#
# This script is idempotent: if .env already exists it will NOT overwrite it,
# so your existing secrets and database data stay intact. Delete .env and
# re-run if you truly want to start over from scratch.

set -euo pipefail

# Always operate relative to the repository root (one level above scripts/).
cd "$(dirname "$0")/.."

ENV_FILE=".env"

if [ -f "$ENV_FILE" ]; then
    echo ".env already exists; leaving it untouched."
    echo "Delete $ENV_FILE and re-run this script to regenerate secrets."
    exit 0
fi

echo "Generating $ENV_FILE ..."

# Hostname devices on your network will use to reach the app. It must resolve
# to this machine (e.g. via mDNS/Avahi). It MUST be served over HTTPS for the
# browser to treat it as a secure context (required for camera access).
SITE_HOST=$(hostname -f)

if [ -z "$SITE_HOST" ]; then
    echo "ERROR: 'hostname -f' returned an empty value." >&2
    echo "Set a resolvable, fully-qualified hostname for this machine first, e.g.:" >&2
    echo "  sudo hostnamectl set-hostname <your-hostname>.local" >&2
    echo "  sudo apt install -y avahi-daemon   # for mDNS resolution over the LAN" >&2
    exit 1
fi

cat > "$ENV_FILE" <<EOF
# ---------------------------------------------------------------------------
# Generated by scripts/init-secrets.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ").
# This file is gitignored. Do NOT commit it.
# ---------------------------------------------------------------------------

# Hostname used to reach the app over the LAN (must resolve to this machine).
SITE_HOST=${SITE_HOST}

# Public HTTPS URL of the frontend; used to build links in outgoing emails.
FRONTEND_BASE_URL=https://${SITE_HOST}

# Port to expose the Mailpit web UI on.
MAILPIT_UI_PORT=8025

# --- MariaDB ---------------------------------------------------------------
DB_NAME=ticketproject_database
DB_USERNAME=ticketproject
DB_PASSWORD=$(openssl rand -hex 24)
MARIADB_ROOT_PASSWORD=$(openssl rand -hex 24)

# --- Application secrets (Base64, 32 random bytes each) --------------------
# Used for encrypting sensitive database fields.
APP_ENCRYPTION_KEY_BASE64=$(openssl rand -base64 32)
# Used for computing blind indexes.
APP_BLIND_INDEX_KEY_BASE64=$(openssl rand -base64 32)
# Used for signing JSON Web Tokens.
APP_JWT_SECRET_BASE64=$(openssl rand -base64 32)

# --- CORS ------------------------------------------------------------------
# Leave empty to keep the API same-origin only (recommended). Add a comma
# separated list of origins if you run a separate frontend against this API.
CORS_ALLOWED_ORIGINS=
EOF

chmod 600 "$ENV_FILE"

echo "Done. Created $ENV_FILE with fresh secrets."
echo "Next: run scripts/make-certs.sh, then 'make up'."
